### ISSUE TITLE
Ubuntu 16.04 Error 

### ISSUE THREAD

**Issue by rjhale1971** [enricofer/go2streetview#24] opened 2016-09-22 00:28 UTC
I tried to install this plugin on 16.04 Ubuntu and received an error. 
***********************************************************************************************
Couldn't load plugin go2streetview due to an error when calling its initGui() method 

TypeError: connect() failed between statusBarMessage(QString) and unislot() 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 342, in startPlugin
    plugins[packageName].initGui()
  File "/home/rjhale/.qgis2/python/plugins/go2streetview/go2streetview.py", line 94, in initGui
    self.view.SV.page().statusBarMessage.connect(self.catchJSevents)
TypeError: connect() failed between statusBarMessage(QString) and unislot()

Python version: 2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609] 
QGIS version: 2.16.2 Nødebo, 979e1a2 

Python Path:
/usr/share/qgis/python/plugins/processing
/usr/share/qgis/python
/home/rjhale/.qgis2/python
/home/rjhale/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/home/rjhale/.local/lib/python2.7/site-packages
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/usr/lib/python2.7/dist-packages/wx-3.0-gtk2
/home/rjhale/.qgis2//python

**Comment by pcav** [comment] 2016-09-22 10:33
Not confirmed here on Debian Sid, QGIS 2.16.2

**Comment by alesarrett** [comment] 2016-09-22 12:21
Confirmed in Ubuntu 16.04, QGIS 2.16.2

**Comment by ghtmtt** [comment] 2016-09-22 13:31
Not confirmed here: Ubuntu 16.04, QGIS 2.17

**Comment by rjhale1971** [comment] 2016-09-22 18:39
The guy I'm helping reported it was working on Ubuntu 16.04 and QGIS 2.14.1. He upgraded to 2.16 and it wasn't so he dropped back to the LTR.

**Comment by enricofer** [comment] 2016-09-23 09:01
I made a quick fix on a temporary branch: https://github.com/enricofer/go2streetview/commit/0870fb721fd3d649f36eef80654e194a456b6a9b
Could you test this: https://github.com/enricofer/go2streetview/archive/signalsTest.zip and give feedback?
Thanks for submissions.

**Comment by rjhale1971** [comment] 2016-09-23 11:55
Installed.
Activated in Plugins Menu. 
When I click on the Map Canvas I am prompted to accept the license agreement for Google/Bing. 
When I click again on the canvas QGIS Crashes. 
I get farther on this version though - so progress. I had no errors being announced. 

I am wondering - could this be a QTWebkit issue (At least I think that is what it is called). QGIS2Web also doesn't work (I think QTWebKit was left out of 2.16 on Ubuntu)

**Comment by enricofer** [comment] 2016-09-26 07:28
As far as i understand, the plugin prompts for agreements and then crashes. But restarting Qgis the plugin is fully operational without errors.
The strange of this issue is that appears only under Ubuntu 16.04, and not on every installation. 
The issue is generated connecting to a signal used by javascript code to give location feedback to python plugin (lat, long,, fov, panorama id) from writing to status bar, that an interface object is a bit outdated for modern Browsers, but yet fully supported by javascript.  It has been fixed exposing python objects to javascript which is the qt supported way for exchanging information and events between python (Qgis) and javascript (Html page).
So something around Qt framework happened. https://github.com/tomchadwin/qgis2web/issues/309
The quick and dirty fix provided will be included in the next Qgis 3.0 / python 3.0 / Qt 5 plugin release.

**Closed by enricofer** 2016-09-26 07:28 UTC
